### ISSUE TITLE
Support reading QE energy band files

### ISSUE THREAD

**Issue by gswylq** [Baijianlu/AICON2#20]
Dear Developers,
 I have successfully obtained the lattice thermal conductivity of a material using AICON2, Quantum ESPRESSO and phonopy, and published a paper (First-principles study on the structural, electronic, elastic and thermal properties of Ag2O2S, 2023). 

I want to calculate the relaxation time and transport properties of electrons using AICON2 and Quantum ESPRESSO, but it seems that only energy band of  vasprun.xml  data can be read using AICON2. Do you have any scripts that support reading QE energy band files?

Looking forward to hearing from you.
Thank you.

Q Li

**Comment by Baijianlu** [comment]
Hello,


Currently I only implemented interface for VASP, but I think it is not a big deal to implement interface for others. No matter which DFT codes one uses, the resulting files are read by pymatgen code. So as long as there is corresponding interface in pymatgen, you can transform the results to the same inner variable in pymatgen.


Regards,

Tao

________________________________
From: gswylq ***@***.***>
Sent: 06 September 2024 04:33:55
To: Baijianlu/AICON2
Cc: Subscribed
Subject: [Baijianlu/AICON2] Support reading QE energy band files (Issue #20)


Dear Developers,
I have successfully obtained the lattice thermal conductivity of a material using AICON2, Quantum ESPRESSO and phonopy, and published a paper (First-principles study on the structural, electronic, elastic and thermal properties of Ag2O2S, 2023).

I want to calculate the relaxation time and transport propertiesof electrons using AICON2 and Quantum ESPRESSO, but it seems that only energy band of vasprun.xml data can be read using AICON2. Do you have any scripts that support reading QE energy band files?

Looking forward to hearing from you.
Thank you.

Q Li
